import SEOHead from '../components/seo/SEOHead'
const S = ({h,children})=>(<div style={{marginBottom:32}}><h2 style={{fontSize:20,fontWeight:800,color:'var(--ink)',marginBottom:12}}>{h}</h2><div style={{fontSize:15,color:'#475569',lineHeight:1.85}}>{children}</div></div>)
export default function TermsPage() {
  return (<>
    <SEOHead title="Terms of Service | Checkupify" description="Checkupify's terms of service — your rights and responsibilities when using our health testing and consultation platform." canonical="https://checkupify.com/terms"/>
    <div style={{background:'linear-gradient(160deg,#f0fdf9,#fff)',padding:'64px 0 32px',textAlign:'center'}}>
      <div className="container" style={{maxWidth:700}}>
        <span className="sec-tag tag-g" style={{display:'inline-flex',marginBottom:16}}>📋 Legal</span>
        <h1 style={{fontSize:'clamp(26px,4vw,40px)',fontWeight:800,color:'var(--ink)',letterSpacing:-.8,marginBottom:16}}>Terms of Service</h1>
        <p style={{color:'var(--slate)',fontSize:14}}>Last updated: April 20, 2026</p>
      </div>
    </div>
    <div style={{padding:'48px 0 80px'}}><div className="container" style={{maxWidth:820}}>
      <S h="1. Acceptance of Terms"><p>By accessing or using Checkupify's platform (checkupify.com), you agree to be bound by these Terms of Service and our Privacy Policy. If you do not agree, please do not use our services. These terms constitute a legally binding agreement between you and Unicribe Technologies Pvt. Ltd.</p></S>
      <S h="2. Services Provided"><p>Checkupify provides a platform to book diagnostic lab tests, health checkup packages, and doctor consultations. We are a technology intermediary connecting patients with NABL-accredited diagnostic labs and qualified medical professionals. Checkupify is not a healthcare provider and does not provide medical advice.</p></S>
      <S h="3. Booking & Payments"><p>All bookings are subject to availability. Payment must be completed to confirm a booking. We accept UPI, credit/debit cards, and net banking via Razorpay. All prices include applicable GST. Checkupify reserves the right to modify prices at any time, but confirmed bookings will honor the price at the time of booking.</p></S>
      <S h="4. Cancellation & Refund Policy"><p>Full refund if: booking is not confirmed within 30 minutes; phlebotomist doesn't arrive within 30 minutes of scheduled time; you cancel at least 2 hours before your appointment. No refund for cancellations less than 2 hours before the appointment (except in verified emergencies). Refunds are processed within 5–7 business days to the original payment method.</p></S>
      <S h="5. Medical Disclaimer"><p>Checkupify is not a substitute for professional medical advice, diagnosis, or treatment. Lab reports are generated by our partner labs. You should always consult a qualified doctor for interpretation of your results and any health concerns. In a medical emergency, please contact emergency services immediately.</p></S>
      <S h="6. Limitation of Liability"><p>Checkupify's total liability for any claim arising from these terms shall not exceed the amount paid by you for the specific service. We are not liable for delays in report delivery due to technical issues or force majeure events.</p></S>
      <S h="7. Governing Law"><p>These Terms are governed by the laws of India. Any disputes shall be subject to the exclusive jurisdiction of courts in Hyderabad, Telangana. For consumer disputes, you may also approach consumer forums under the Consumer Protection Act, 2019.</p></S>
      <S h="8. Contact"><p>For legal matters: legal@checkupify.com<br/>Unicribe Technologies Pvt. Ltd., Jubilee Hills, Hyderabad, Telangana 500033</p></S>
    </div></div>
  </>)
}
